### ISSUE TITLE
Response encoding is going to bite us (really, me)

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#102]
instrument variables have been response-shifted/remapped in order to align them with instrument variables in other instruments. There are many cases where the exact same variable in several instruments has different response encodings, such as “0” and “1” for “No” and “Yes”, or “1” and “2”, or “Y” and “N”, etc. This has historically been handled by flagging pairs of equivalent variables (which are ultimately merged into equivalence groups) with a pointer to the series of steps required to change the encoding of the 2nd variable to the same as the 1st (typically to the dominant first member’s mapping).

This won't fly. I had this in separate databases (mostly? I think?), i.e., DIGS_cleaned and DIGS_harmonized, because I didn't want to actually modify the responses in the database, as that is bad. Now I might be stuck. Do we need the original values still accessible in DIVER? Should be we be using DIGS_harmonized instead of DIGS_cleaned? If we put another prefixed variable in there for the remapped responses, what happens when a cohort includes both?  Ugh. This needs thought and discussion.

**Comment by Viqsi** [comment]
From the user perspective w/r/t categorical variables like the examples described, I'm frankly not showing them Actual Values unless it absolutely can't be helped (i.e. if there's no "response mapping" in the database; in that case I'm showing the validation regex and its description and clearly marking it as such). I don't know if that helps or complicates your work on this.

I will freely admit I would prefer not to have to worry about this on my end... :D

**Comment by Viqsi** [comment]
It occurs to me that we're already doing a great deal of encoding mishegaas with metavalues like Unknown ("[UNK]") already *in* the DIVER_ref database, so that to me suggests we're already making use of DIGS_harmonized to build that thing. Or perhaps I'm misunderstanding what database does what...

Some part of me wants to suggest a Universal Answer Encoding scheme for all possible categorical answers to all questions but that would undoubtedly require more time/money/personnel than we have...

**Comment by WValenti** [comment]
This is resolved by implementing the encoding conversions on the original variables to produce new NRGR_<original variable_name> variables in the DIGS database tables, and changing the participation in harmonization from the original to the new NRGR_ variable. See CAPSDB/NRGR_b2a for scripting.
