### ISSUE TITLE
Downcoding a numberrange variable using BETWEEN prompts fine but blows-up when saving

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#104]
![Screen Shot 2023-02-22 at 12 52 18 PM](https://user-images.githubusercontent.com/3909236/220713924-18d5a67d-d9a8-4442-bf0f-7897e9cb57b7.png)

**Comment by Viqsi** [comment]
Had no relation whatsoever to #58; was taken care of with MathematicalMedicine/diverweb@fc08b40
