### ISSUE TITLE
Construct Variable names currently required to be unique across user projects

### ISSUE THREAD

**Issue by Viqsi** [MathematicalMedicine/diver-issues#160]
See #158 - this issue is also present in the `construct_variables` table.

Indeed, it's arguably even more awkward - the key entry for that table is ```KEY `owner` (`owner`,`variable_name`)```; not only does it exclude `projectId`, it's not explicity specified as UNIQUE either.

**Comment by WValenti** [comment]
I think they should be unique across the entire system. Reuse of names could cause tremendous confusion, and is not necessary. Variables can and will be ultimately shared, and everyone and everything expects them to be the same when they are named the same.  This is not the same situation with cohorts.

**Comment by Viqsi** [comment]
The concern there is going to be user feedback and expectations - "I know I didn't create a variable by that name; why is it telling me no?"

That does make me wonder if it would be prudent to prefix construct variables with one's username (`jvc_ConstructVariable`). It'd open a new can of worms w/r/t copying constructs (and things dependent on those constructs) between users and What Is Proper Protocol In That Situation, though.

**Comment by Viqsi** [comment]
Bonus Complication: construct_variable_response_mappings is keyed just by variable *name*, not ID. This has Special Bonus Fun Implications, particularly when, say, deleting a no longer wanted construct.

Beginning to think username prefixing might be a more worthy idea. :(

**Comment by Viqsi** [comment]
Fixed in MathematicalMedicine/diverRPC@f22a737
