### ISSUE TITLE
PDF instrument offsets to the proper page for each variable are wrong in many places

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#171]
The page offset into the instrument PDF is constructed from two values:  1) the instrument-wide offset (generally a very small number if not zero), and the offset to the page for the variable in question.  This needs a bit of cleaning-up, but has one significant design issue -- I have presumed that some instruments are merely offset versions of others when that is not the case. The one I know is a problem for sure is DIGS 1.0 vs DIGS 2.0. This must be addressed by splitting-out and correcting a DIGS 1.0-specific version in DIGS_questions (where the variable-specific offsets are located).

**Comment by Viqsi** [comment]
This looks like it could be the same bug #144, although that one is about PDFs for other instruments.

**Comment by WValenti** [comment]
Three instruments needed full offset repair, and a fourth looked suspicious but was fine. We NO LONGER USE DIGS_versions.codebook_page_offset BUT I'm leaving it in the databases as all zeroes just in case something somewhere remembers it (so it'll be incorrectly-offset instead of crash). This is database change #45.
