### ISSUE TITLE
ada MariaDB database locks-up when long-running updates are performed.

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#180]
This first occurred during updates of DIGS_cleaned.kibble by the make_DIVER scripts, and required a reboot and some "quiet" time to clear. It has also occurred during simple restorations of large databases. Jo has researched this down to a known problem in MariaDB which is present in all? versions. It is not particularly dependent upon maxwell's daemon running, but as that adds to the workload, doing so during heavy updates increases the likelihood of the problem

We are currently NOT confident with our production platform, but have little other choice but to keep using it.

**Comment by Viqsi** [comment]
This appears to have been fixed by basically "restarting the DB from scratch" - backing up user data, then wiping the existing DB, recreating it, regenerating the DIVER tables, and restoring user data. Therefore, closing.
