### ISSUE TITLE
V426 (and possibly other variables) seemingly missing `question_id` values

### ISSUE THREAD

**Issue by Viqsi** [MathematicalMedicine/diver-issues#189]
I was doing a check of search results and the results' Question/Description fields looked a bit sparse. (See for example I17673 on this page):

![image](https://github.com/MathematicalMedicine/diver-issues/assets/6570923/823e6f1d-968e-474f-a0e5-ce0d81efd185)

V426 (further down in results, not in the above screenshot) in particular looked especially odd.

![image](https://github.com/MathematicalMedicine/diver-issues/assets/6570923/212abfc3-5ed5-43f4-9539-ffec81bdf32d)

The italic text is "explicit context", but there should also be question text, normally. I checked in the PDF, and sure enough, it's supposed to have question text. (It's item 4.c on this page). Curiously, the question text *does* include the "depressed" keyword which I searched for, but it's not displaying.

![image](https://github.com/MathematicalMedicine/diver-issues/assets/6570923/4516f4fd-1cda-4cfd-908f-98d5b92d0f01)

I tracked this down to `question_id` in `DIGS_questions` being NULL for that variable:

![image](https://github.com/MathematicalMedicine/diver-issues/assets/6570923/427a158b-e109-47de-b9d2-66885be2bed5)

And that's where @WValenti comes in - figuring out how/why that ended up NULL.

**Comment by WValenti** [comment]
`Select count(*), variable_name from DIGS_questions where section <> 'meta' AND question_id = 1 group by variable_name order by count(*) desc;`
Many of these are expected, but some aren't, so will investigate.

**Comment by WValenti** [comment]
NRGR ones are out (for now), as are most "funky" numbered names, as I added those manually for various reasons.

**Comment by WValenti** [comment]
Search in DIVER explodes:
I16060

There is no question, but explicit context is sufficent to use by itself:
I10970
I310
I14300
I1590

Not really anywhere except variables:
pan_noag
socphob
pan_ag
sads3r
...looks like all of the lowercase-only ones are garbage.
ocd
revid
oads
r002
id
ptsd
gad
panic
specphob
agor

Known exception that still needs intervention:
NOT_I5970

**Comment by WValenti** [comment]
Delete from variables where observations = 0 AND variable_name IN ('pan_noag', 'socphob', 'pan_ag', 'sads3r', 'ocd', 'revid', 'oads', 'r002', 'id', 'ptsd', 'gad', 'panic', 'specphob', 'agor');

INSERT INTO questions_and_contexts (question_and_context_text, source_version, source_variable_name) VALUES ('Narrative Summary of Interviewer\' Reliability Assessment', '2.0', 'I17672');
SELECT MAX(question_and_context_id) FROM questions_and_contexts; -- 34803
UPDATE DIGS_questions SET question_id = 34803 WHERE variable_name = 'I17672';

I6060 no longer explodes DIVER -- must have gotten it at a bad time.
