### ISSUE TITLE
DIVER documentation as a booklet

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#209]
I suggest we:

1. Initially produce VV's documentation as a single PDF and jump to the appropriate page for whatever topic they click for help on just like we do for variables in instruments.
2. VV wants an INTERNAL TOC for the document, but that may not be easily done, so I think we should only look into this lightly.
3. This document doesn't have to be cohesive initially, but it could later be fleshed-out to become documentation provided separately to users or as an introduction to DIVER.

**Comment by Viqsi** [comment]
I'm doing it in Word right now. Something shinier will probably be appropriate at some later time.

**Comment by Viqsi** [comment]
It's done. Not currently tracked in a repo, but at the moment doesn't have to be. Will move on to a better embedded docs system later.
