### ISSUE TITLE
Download Data page on Selected Variable Set has two "trash cans"

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#234]
This just seems strange:
![Screen Shot 2024-05-01 at 7 21 43 AM](https://github.com/MathematicalMedicine/diver-issues/assets/3909236/b7ec8ace-ca56-4e26-a4f9-7bdba072b74a)

**Comment by Viqsi** [comment]
I'm pretty sure this is a redundancy in specifying variable actions for that variables table. The concern is that I think one of them is "remove this variable set from the download and pick another one" and the other (automatic) one would be "delete this variable set entirely". Which is a problem.
