### ISSUE TITLE
A trailing space when creating, for example, a project, cannot be seen but must be specified to allow deletion

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#50]
Try deleting the project "Nothing to see here, move along" without adding a trailing space.

**Comment by Viqsi** [comment]
Have also previously experienced this with cohort deletion, so it's common to all uses of the "enter the name to confirm" approach.

**Comment by Viqsi** [comment]
The more I consider this the more I'm tempted to just mark it WONTFIX and move on. It's an extremely trivial thing for which the user has to shoot themselves in the foot, pause, aim, and shoot a second time, and actually correcting it would be more trouble than it's possibly worth.

**Comment by Viqsi** [comment]
I'm succumbing to the aforementioned temptation.
