### ISSUE TITLE
Creating a cohort w/CONTAINS constraint crashes webapp

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#8]
![Screen Shot 2022-03-02 at 12 04 18 PM](https://user-images.githubusercontent.com/3909236/156412777-7bfcc0da-5f70-4149-bdc1-62a468d9bb04.png)

**Comment by Viqsi** [comment]
CONTAINS turns out to *not* be one of ours, but rather a Digital Wave creation, which is Not Yet Implemented. See #25.

**Comment by Viqsi** [comment]
Closing this one as CONTAINS isn't getting used; it's an alias for REGEX and REGEX has been fine, so if it goes bad again that's a separate issue.
