### ISSUE TITLE
Create Cohort preview not updated when changing constraint gives 0 (zero) individuals

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diver-issues#96]
I first constrained SEX to EXISTS and got all individuals returned.  I then changed the constraint to EQUALS "x" and got 0 rows, which is correct, but the display of individuals remained unchanged:

![Screen Shot 2023-02-09 at 1 34 28 PM](https://user-images.githubusercontent.com/3909236/217906398-eca2e4fa-34bc-458f-847d-b7380d242104.png)

**Comment by Viqsi** [comment]
This also appears to affect previews of compound cohorts as well, so it's something in that component (or something in how that component is being consistently used).

**Comment by Viqsi** [comment]
This appears to have been fixed as part of adding 'loading' spinners to the previews. Huzzah!
